@host = http://127.0.0.1:8000
@api_prefix = /api

### 0-1. 'superadmin' 권한을 가진 사용자 로그인
# 이 사용자로 다른 사용자의 정보를 수정/변경할 것입니다.
POST {{host}}{{api_prefix}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=sontest&password=1234567

> {%
    client.global.set("superadmin_token", "Bearer " + response.body.access_token);
    client.global.set("customer_id", "admin03");
%}


### 국가입력
POST {{host}}{{api_prefix}}/countries/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "country_name": "대한민국9"
}


### 국가 삭제
DELETE {{host}}{{api_prefix}}/countries/15

### 브랜드 삭제
DELETE {{host}}{{api_prefix}}/brands/4

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/portfolio/list?page=1&size=5&design_name=v

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/released-product/list?page=1&size=5&design_name=v

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/portfolio/SIMPLE_BLUE_V188

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?code_name=V21

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?status=Brown

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?clo=Brown

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?start_date=2023-10-01&end_date=2023-10-31

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?page=2&size=20&status=A&color_name=Red&start_date=2023-01-01




### 1. 출시제품 추가
POST {{host}}{{api_prefix}}/released-product/
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="released_product"
Content-Type: application/json

{
  "design_name": "SIMPLE_BLUE_V4",
  "color_name": "심플 블루 테마 버전2",
  "main_image_url": "public_url",
  "brand": {
  "id": 1,
  "brand_name": "지라2",
  "brand_image_url": "http://localhost:9000/images/uploads/500fdb3a-1215-4139-a056-c8edb9711cb4.png"
  },
  "color_line": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },
  "color_base1": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },
  "color_base2": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },
  "color_pupil": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 50
  },
  "graphic_diameter": "13.2mm",
  "optic_zone": "10mm",
  "base_curve": "8.6"
}

--boundary
Content-Disposition: form-data; name="file"; filename="summer_sea.png"
Content-Type: image/png

< G:/image.png
--boundary--



### 1. 새로운 포트폴리오 생성 (JSON + 파일 동시 전송)
POST {{host}}{{api_prefix}}/portfolio/
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="portfolio"
Content-Type: application/json

{
  "design_name": "SIMPLE_BLUE_V117",
  "color_name": "심플 블루 테마 버전2",
  "exposed_countries":  {
    "대한민국5": 17,
    "미국": 6,
    "중국": 5,
    "호주": 4,
    "캐나다": 3,
    "인도": 2,
    "베트남": 1,
    "러시아": 10
  },
  "is_fixed_axis": true,
  "main_image_url": "public_url",

  "design_line": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },

  "design_base1": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },

  "design_base2": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },

  "design_pupil": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 50
  },

  "graphic_diameter": "13.2mm",
  "optic_zone": "10mm"
}

--boundary
Content-Disposition: form-data; name="file"; filename="summer_sea.png"
Content-Type: image/png

< G:/image.png
--boundary--




### 1-1. 첫 번째 디자인 생성
POST {{host}}{{api_prefix}}/custom-designs/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "code_name": "SIMPLE_BLUE_V20",
  "design_name": "심플 블루 테마 버전2",
  "request_message": "코가 편안한 파란색으로 만들어주세요.",

  "design_line": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },

  "design_base1": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },

  "design_base2": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 100
  },

  "design_pupil": {
    "image_id": "1",
    "image_url": "dsaklfjdslakjfalksdjfksa",
    "image_name": "L-1000",
    "RGB_id": "10",
    "RGB_color": "00ff00",
    "RGB_name": "C-1000",
    "size": 100,
    "opacity": 50
  },

  "graphic_diameter": "13.2mm",
  "optic_zone": "10mm"
}


