@host = http://127.0.0.1:8000
@api_prefix = /api

### 0-1. 'superadmin' 권한을 가진 사용자 로그인
# 이 사용자로 다른 사용자의 정보를 수정/변경할 것입니다.
POST {{host}}{{api_prefix}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=sontest&password=1234567

> {%
    client.global.set("superadmin_token", "Bearer " + response.body.access_token);
    client.global.set("customer_id", "admin03");
%}


### 국가입력
POST {{host}}{{api_prefix}}/countries/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "country_name": "일본"
}


### 국가 삭제
DELETE {{host}}{{api_prefix}}/countries/15

### 브랜드 삭제
DELETE {{host}}{{api_prefix}}/brands/4

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/portfolio/list?page=1&size=5&design_name=v

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/released-product/list?page=1&size=5&design_name=v

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/portfolio/SIMPLE_BLUE_V188

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?code_name=V21

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?status=Brown

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?clo=Brown

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?start_date=2023-10-01&end_date=2023-10-31

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?page=2&size=20&status=A&color_name=Red&start_date=2023-01-01


