#Api함수 제작

### 랭킹 목록
GET {{host}}{{api_prefix}}/v1/rank/


### 커스텀 디자인 목록
GET {{host}}{{api_prefix}}//custom-designs/list?page=1&size=10
###
GET {{host}}{{api_prefix}}//custom-designs/1
###
GET {{host}}{{api_prefix}}//custom-designs/info/1


### 출시제품 목록
GET {{host}}{{api_prefix}}/released-product/info/2
###
GET {{host}}{{api_prefix}}/released-product/list


### 포트폴리오 목록
GET {{host}}{{api_prefix}}/portfolio/info/2
###
GET {{host}}{{api_prefix}}/portfolio/list





### 국가 삭제
DELETE {{host}}{{api_prefix}}/countries/15

### 국가 목록
GET {{host}}{{api_prefix}}/countries/listall

### 콤바인 목록
GET {{host}}{{api_prefix}}/combined-data/

### 브랜드 목록
GET {{host}}{{api_prefix}}/brands/listall

### 브랜드 삭제
DELETE {{host}}{{api_prefix}}/brands/4

### 컬러 삭제
DELETE {{host}}{{api_prefix}}/colors/11

### 컬러 생성
POST {{host}}{{api_prefix}}/colors/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "color_name": "12349",
  "monochrome_type": "1",
  "color_values": "255,0,0,0,100,100,0"
}


###
POST {{host}}{{api_prefix}}/released-product/
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="design_name"

새로운 겨울 디자인 20252
--boundary
Content-Disposition: form-data; name="color_name"

프로스트 실버
--boundary
Content-Disposition: form-data; name="brand_id"

3
--boundary
Content-Disposition: form-data; name="color_line_color_id"

31
--boundary
Content-Disposition: form-data; name="color_base1_color_id"

33
--boundary
Content-Disposition: form-data; name="color_base2_color_id"

35
--boundary
Content-Disposition: form-data; name="color_pupil_color_id"

40
--boundary
Content-Disposition: form-data; name="graphic_diameter"

13.8mm
--boundary
Content-Disposition: form-data; name="optic_zone"

8.1mm
--boundary
Content-Disposition: form-data; name="base_curve"

8.8
--boundary
Content-Disposition: form-data; name="file"; filename="winter_frost.png"
Content-Type: image/png

< G:/image.png
--boundary--






###
PATCH {{host}}{{api_prefix}}/released-product/1
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="design_name"

최종 수정된 겨울 디자인2
--boundary
Content-Disposition: form-data; name="color_name"

최종 프로스트 실버
--boundary
Content-Disposition: form-data; name="brand_id"

5
--boundary
# ... (다른 수정할 텍스트 필드들) ...
--boundary
Content-Disposition: form-data; name="file"; filename="new_winter_image.jpg"
Content-Type: image/jpeg

< G:/image.png
--boundary--



### 국가입력
POST {{host}}{{api_prefix}}/countries/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "country_name": "미국"
}

### 포트폴리오 리스트
GET {{host}}{{api_prefix}}/portfolio/list?page=1&size=5

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/list?item_name=S

### 디자인 전부 출력
PATCH {{host}}{{api_prefix}}/custom-designs/status/1
Content-Type: application/json
Authorization: {{superadmin_token}}

   {
     "status": "승인됨"
   }

### 출시제품 전부 출력
GET {{host}}{{api_prefix}}/released-product/list

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/released-product/list?page=1&size=5

### 포트폴리오 이름 확인
GET {{host}}{{api_prefix}}/portfolio/SIMPLE_BLUE_V188

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?code_name=V21

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?status=Brown


### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?start_date=2023-10-01&end_date=2023-10-31

### 디자인 전부 출력
GET {{host}}{{api_prefix}}/custom-designs/?page=2&size=20&status=A&color_name=Red&start_date=2023-01-01
