
### 0-1. 'superadmin' 권한을 가진 사용자 로그인
POST {{host}}{{api_prefix}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=sontest&password=1234567

> {%
    client.global.set("superadmin_token", "Bearer " + response.body.access_token);
    client.global.set("code", response.body.account_code + "-");
%}


### 0-1. 'superadmin' 권한을 가진 사용자 로그인
POST {{host}}{{api_prefix}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=123456

> {%
    client.global.set("superadmin_token", "Bearer " + response.body.access_token);
    client.global.set("code", response.body.account_code + "-");
%}




### 계정 등록
POST {{host}}{{api_prefix}}/auth/register
Content-Type: application/json

{
    "permission": "superadmin",
    "username": "sontest",
    "password": "1234567",
    "email": "bba1@gmail.com",
    "company_name": "넷스트림",
    "contact_name": "홍길동",
    "contact_phone": "01022334455",
    "account_code": "DA"
}




### 컬러 생성
POST {{host}}{{api_prefix}}/colors/
Content-Type: application/json

{
  "color_name": "주황3",
  "monochrome_type": "컬러",
  "color_values": "255,0,0,0,100,100,0"
}




### 브랜드 생성
POST {{host}}{{api_prefix}}/brands/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="brand_name"

유니클로
--boundary
Content-Disposition: form-data; name="file"; filename="prospecs_new.png"

< G:/image.png
--boundary--




### 국가 생성
POST {{host}}{{api_prefix}}/countries/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "country_name": "대한민국9"
}





### 1. 새로운 포트폴리오 생성 (JSON + 파일 동시 전송)
POST {{host}}{{api_prefix}}/portfolio/
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="portfolio"
Content-Type: application/json

{
  "design_name": "SIMPLE_BLUE_110",
  "color_name": "심플 블루 테마 버전2",
  "exposed_countries":  "1,2,3,4,5",
  "is_fixed_axis": "Y",
  "design_line_image_id": "1",
  "design_line_color_id": "10",
  "design_base1_image_id": "2",
  "design_base1_color_id": "11",
  "design_base2_image_id": "3",
  "design_base2_color_id": "12",
  "design_pupil_image_id": "4",
  "design_pupil_color_id": "13",
  "graphic_diameter": "13.2mm",
  "optic_zone": "10mm"
}

--boundary
Content-Disposition: form-data; name="file"; filename="summer_sea.png"
Content-Type: image/png

< G:/image.png
--boundary--



### 1. 포트폴리오 업데이트 (JSON + 파일 동시 전송)
PATCH {{host}}{{api_prefix}}/portfolio/1
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="portfolio"
Content-Type: application/json

{
  "design_name": "SIMPLE_BLUE_V112",
  "color_name": "심플 블루 테마 버전2",
  "exposed_countries": "1,2,3,4,5",
  "is_fixed_axis": "Y",
  "design_line_image_id": "1",
  "design_line_color_id": "10",
  "design_base1_image_id": "2",
  "design_base1_color_id": "11",
  "design_base2_image_id": "3",
  "design_base2_color_id": "12",
  "design_pupil_image_id": "4",
  "design_pupil_color_id": "13",
  "graphic_diameter": "13.2mm",
  "optic_zone": "10mm"
}

--boundary
Content-Disposition: form-data; name="file"; filename="summer_sea.png"
Content-Type: image/png

< G:/image.png
--boundary--



### 1-1. 첫 번째 디자인 생성
POST {{host}}{{api_prefix}}/custom-designs/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "request_message": "코가 편안한 파란색으로 만들어주세요.",
  "design_line_image_id": "1",
  "design_line_color_id": "10",
  "design_base1_image_id": "2",
  "design_base1_color_id": "11",
  "design_base2_image_id": "3",
  "design_base2_color_id": "12",
  "design_pupil_image_id": "4",
  "design_pupil_color_id": "13",
  "graphic_diameter": "13.2mm",
  "optic_zone": "10mm"
}



