
### 0-1. 'superadmin' 권한을 가진 사용자 로그인
POST {{host}}{{api_prefix}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=sontest&password=1234567

> {%
    client.global.set("superadmin_token", "Bearer " + response.body.access_token);
    client.global.set("code", response.body.account_code + "-");
%}


### 0-1. 'superadmin' 권한을 가진 사용자 로그인
POST {{host}}{{api_prefix}}/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=123456

> {%
    client.global.set("superadmin_token", "Bearer " + response.body.access_token);
    client.global.set("code", response.body.account_code + "-");
%}




### 계정 등록
POST {{host}}{{api_prefix}}/auth/register
Content-Type: application/json

{
    "permission": "superadmin",
    "username": "sontest",
    "password": "1234567",
    "email": "bba1@gmail.com",
    "company_name": "넷스트림",
    "contact_name": "홍길동",
    "contact_phone": "01022334455",
    "account_code": "DA"
}




### 컬러 생성
POST {{host}}{{api_prefix}}/colors/
Content-Type: application/json

{
  "color_name": "주황3",
  "monochrome_type": "컬러",
  "color_values": "255,0,0,0,100,100,0"
}




### 브랜드 생성
POST {{host}}{{api_prefix}}/brands/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="brand_name"

유니클로
--boundary
Content-Disposition: form-data; name="file"; filename="prospecs_new.png"

< G:/image.png
--boundary--




### 국가 생성
POST {{host}}{{api_prefix}}/countries/
Content-Type: application/json
Authorization: {{superadmin_token}}

{
  "country_name": "대한민국9"
}





### 1. 새로운 포트폴리오 생성
POST {{host}}{{api_prefix}}/portfolio/
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="design_name"

SIMPLE_BLUE_1292
--boundary
Content-Disposition: form-data; name="color_name"

심플 블루 테마 버전2
--boundary
Content-Disposition: form-data; name="exposed_countries"

1,2,3,4,5
--boundary
Content-Disposition: form-data; name="is_fixed_axis"

Y
--boundary
Content-Disposition: form-data; name="design_line_image_id"

1
--boundary
Content-Disposition: form-data; name="design_line_color_id"

10
--boundary
Content-Disposition: form-data; name="design_base1_image_id"

2
--boundary
Content-Disposition: form-data; name="design_base1_color_id"

11
--boundary
Content-Disposition: form-data; name="design_base2_image_id"

3
--boundary
Content-Disposition: form-data; name="design_base2_color_id"

12
--boundary
Content-Disposition: form-data; name="design_pupil_image_id"

4
--boundary
Content-Disposition: form-data; name="design_pupil_color_id"

13
--boundary
Content-Disposition: form-data; name="graphic_diameter"

13.2mm
--boundary
Content-Disposition: form-data; name="optic_zone"

10mm
--boundary
Content-Disposition: form-data; name="file"; filename="summer_sea.png"
Content-Type: image/png

< G:/image.png
--boundary--



### 1. 포트폴리오 업데이트
PATCH {{host}}{{api_prefix}}/portfolio/1
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="design_name"

수정된_디자인_이름
--boundary
Content-Disposition: form-data; name="color_name"

수정된 컬러 이름
--boundary
Content-Disposition: form-data; name="exposed_countries"

1,2,5,8
--boundary
Content-Disposition: form-data; name="is_fixed_axis"

N
--boundary
Content-Disposition: form-data; name="graphic_diameter"

13.5mm
--boundary
Content-Disposition: form-data; name="optic_zone"

10.2mm
--boundary
# 이미지를 변경하고 싶지 않으면 'file' 파트를 보내지 않으면 됩니다.
# 이미지를 변경하려면 아래 파트를 추가합니다.
Content-Disposition: form-data; name="file"; filename="new_image.jpg"
Content-Type: image/jpeg

< G:/image.png
--boundary--








### 디자인 생성
POST {{host}}{{api_prefix}}/custom-designs/
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="request_message"

코가 편안한 파란색으로 만들어주세요.
--boundary
Content-Disposition: form-data; name="design_line_image_id"

1
--boundary
Content-Disposition: form-data; name="design_line_color_id"

10
--boundary
Content-Disposition: form-data; name="design_base1_image_id"

2
--boundary
Content-Disposition: form-data; name="design_base1_color_id"

11
--boundary
Content-Disposition: form-data; name="design_base2_image_id"

3
--boundary
Content-Disposition: form-data; name="design_base2_color_id"

12
--boundary
Content-Disposition: form-data; name="design_pupil_image_id"

4
--boundary
Content-Disposition: form-data; name="design_pupil_color_id"

13
--boundary
Content-Disposition: form-data; name="line_transparency"

50
--boundary
Content-Disposition: form-data; name="base1_transparency"

50
--boundary
Content-Disposition: form-data; name="base2_transparency"

50
--boundary
Content-Disposition: form-data; name="pupil_transparency"

50
--boundary
Content-Disposition: form-data; name="graphic_diameter"

13.2mm
--boundary
Content-Disposition: form-data; name="optic_zone"

10mm
--boundary
# 이미지를 변경하고 싶지 않으면 'file' 파트를 보내지 않으면 됩니다.
# 이미지를 변경하려면 아래 파트를 추가합니다.
Content-Disposition: form-data; name="file"; filename="new_image.jpg"
Content-Type: image/jpeg

< G:/image.png
--boundary--





###  디자인 패치
PATCH {{host}}{{api_prefix}}/custom-designs/info/15
Content-Type: multipart/form-data; boundary=boundary
Authorization: {{superadmin_token}}

--boundary
Content-Disposition: form-data; name="request_message"

요청 메시지를 이걸로 수정합니다.
--boundary
Content-Disposition: form-data; name="graphic_diameter"

14.2mm
--boundary--