

### 유니티 사용자 로그인
POST {{host}}{{api_prefix}}/login/
Content-Type: application/x-www-form-urlencoded

username=sontest&password=1234567

> {%
    client.global.set("superadmin_token", "Bearer " + response.body.access_token);
    client.global.set("my_refresh_token", response.body.refresh_token);
    client.global.set("code", response.body.account_code + "-");
%}



### 메일 보내기
POST {{host}}{{api_prefix}}/mail/send-email
Content-Type: application/json

{
  "to_email": "mrsonno1@naver.com",
  "subject": "안녕하세요",
  "body": "테스트 메일입니다."
}

### 유저 정보
GET {{host}}{{api_prefix}}/login/me
Authorization: {{superadmin_token}}


### 업데이트
PUT {{host}}{{api_prefix}}/login/me
Authorization: {{superadmin_token}}
Content-Type: application/json

{
  "company_name": "string",
  "contact_name": "string",
  "contact_phone": "string",
  "email": "user@example.com",
  "new_password": "1234567"
}


### 리프레쉬
POST {{host}}{{api_prefix}}/login/refresh
refresh-token: {{my_refresh_token}}
